from jarvis import speak
print("Some of my functions are: 																																				")
print(" 1. If you speak something with the word 'wikipedia' I will automatically search and summarize a suitable answer")
print(" 2. If you speak something with the word 'open' the words corresponding will analyzed example if you say 'open Chrome' or any other app then chrome will be open")
print("													 'open youtube' or any other website it will be opened")
print(" 3. If you speak 'the time' the current time of your location will displayed")
print(" 4. If you speak 'send an email' then the sendEmail function will start / you can only send emails to people in the dictionary")
print(" 5. If you speak 'send a whatsapp message' then the SendWhatsappmsg function will become active again you can only send messages to people specified in the dictionary")
print(" 6. If you speak 'on youtube' the corresponding words will be searched on youtube")
print(" 7. If you speak 'on google' the corresponding words will be searched on google")
print(" 8. If you speak 'record screen' then your screen will start to record(still beta/underdevelopment)")
print(" 9. If you speak 'who am i' then the data stored in the txt file 'pd' will be used(make sure yiu write your data)")
print(" 10.If you speak 'set an alarm' the alarm function will be triggered")
print(" 11.If you speak 'set a reminder' then a function which sets reminder will trigger")
print(" 12.If you speak 'reminder' then any reminder scheduled for today will be displayed")

speak("Some of my functions are: 																																						")
speak(" 1. If you speak something with the word 'wikipedia' I will automatically search and summarize a suitable answer")
speak(" 2. If you speak something with the word 'open' the words corresponding will analyzed example if you say 'open Chrome' or any other app then chrome will be open")
speak("													 'open youtube' or any other website it will be opened")
speak(" 3. If you speak 'the time' the current time of your location will displayed")
speak(" 4. If you speak 'send an email' then the sendEmail function will start / you can only send emails to people in the dictionary")
speak(" 5. If you speak 'send a whatsapp message' then the SendWhatsappmsg function will become active again you can only send messages to people specified in the dictionary")
speak(" 6. If you speak 'on youtube' the corresponding words will be searched on youtube")
speak(" 7. If you speak 'on google' the corresponding words will be searched on google")
speak(" 8. If you speak 'record screen' then your screen will start to record(still beta/underdevelopment)")
speak(" 9. If you speak 'who am i' then the data stored in the txt file 'pd' will be used(make sure yiu write your data)")
speak(" 10.If you speak 'set an alarm' the alarm function will be triggered")
speak(" 11.If you speak 'set a reminder' then a function which sets reminder will trigger")
speak(" 12.If you speak 'reminder' then any reminder scheduled for today will be displayed")
