import os
print("This program will install all modules and libraries required to run Jarvis")
print("This will take time")
os.system('pip install pyttsx3')
os.system('cls')
os.system('pip install datetime')
os.system('cls')
os.system('pip install speech_recognition') 
os.system('cls')
os.system('pip install wikipedia')
os.system('cls')
os.system('pip install webbrowser')
os.system('cls')
os.system('pip install smtplib')
os.system('cls')
os.system('pip install numpy')
os.system('cls')
os.system('pip install PIL')
os.system('cls')
os.system('pip install winsound')
os.system('cls')
os.system('pip install win32api')
os.system('cls')
os.system('pip install cv2')
os.system('cls')
os.system('pip install time')
os.system('cls')
print("All of them are installed!")
